"""``TOOLS.md`` and the README tool-count table must match the live registry.

Both are generated by ``scripts/gen_tools_md.py`` from ``mcp.list_tools()`` and
:data:`~word_document_server.tools.platforms.PLATFORMS` -- see that script's
module docstring for why: three different, wrong tool counts had drifted apart
(README 124/80/44/40, ``TOOLS.md`` 115, ``manifest.json`` 114) before this
guard existed. A contributor who adds a tool without regenerating the docs now
fails a test with a fix-it message instead of leaving another silently stale
count behind.
"""

from __future__ import annotations

import importlib.util
import subprocess
import sys
from pathlib import Path
from types import ModuleType

REPO_ROOT = Path(__file__).resolve().parent.parent


def _load_gen_tools_md() -> ModuleType:
    """Import ``scripts/gen_tools_md.py`` as a module (the `scripts` dir is not a package)."""
    path = REPO_ROOT / "scripts" / "gen_tools_md.py"
    spec = importlib.util.spec_from_file_location("gen_tools_md", path)
    assert spec is not None and spec.loader is not None
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module


def test_check_flag_passes_on_the_committed_docs():
    """The exact acceptance command: a contributor who forgets to regenerate sees this fail."""
    result = subprocess.run(
        [sys.executable, str(REPO_ROOT / "scripts" / "gen_tools_md.py"), "--check"],
        cwd=REPO_ROOT,
        capture_output=True,
        text=True,
        check=False,
    )
    assert result.returncode == 0, (
        "TOOLS.md and/or README.md have drifted from the tool registry; "
        "run `python scripts/gen_tools_md.py` to regenerate them.\n"
        f"stdout:\n{result.stdout}\nstderr:\n{result.stderr}"
    )


def test_readme_keeps_its_tool_count_markers():
    """`apply_readme_counts` needs both markers; losing one should fail loudly, not silently."""
    gen_tools_md = _load_gen_tools_md()
    readme_text = (REPO_ROOT / "README.md").read_text(encoding="utf-8")
    assert gen_tools_md.README_MARKER_START in readme_text
    assert gen_tools_md.README_MARKER_END in readme_text
    assert readme_text.index(gen_tools_md.README_MARKER_START) < readme_text.index(
        gen_tools_md.README_MARKER_END
    )


def test_tools_md_lists_every_registered_tool_exactly_once():
    gen_tools_md = _load_gen_tools_md()
    tools = gen_tools_md._load_tools()
    tools_md = gen_tools_md.render_tools_md(tools)
    for tool in tools:
        needle = f"`{tool.name}`"
        assert tools_md.count(needle) == 1, f"{tool.name} should appear exactly once in TOOLS.md"


def test_readme_snippet_totals_match_the_registry():
    gen_tools_md = _load_gen_tools_md()
    tools = gen_tools_md._load_tools()
    snippet = gen_tools_md.render_readme_counts(tools)
    assert f"**{len(tools)} tools**" in snippet
